name: Deploy to AWS Elastic Beanstalk with Docker

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: your-docker-username/athenium-server:$GITHUB_SHA
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Athenium \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-2-767398068141",S3Key="Athenium/$GITHUB_SHA.zip" \
            --auto-create-application \
            --process

      - name: Deployment Complete
        run: echo App deployed to AWS Elastic Beanstalk
