name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Adjust region as needed

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name Athenium --version-label $GITHUB_SHA --source-bundle S3Bucket="elasticbeanstalk-us-east-2-123456789012",S3Key="your-app-name/$GITHUB_SHA.zip"
          aws elasticbeanstalk update-environment --application-name Athenium --environment-name Athenium-env --version-label $GITHUB_SHA

      - name: Deployment Complete
        run: echo App deployed to AWS Elastic Beanstalk
