name: Deploy to AWS Elastic Beanstalk with Docker

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use Node.js version 20.x or another compatible version

      - name: Update npm to version 10.8.2
        run: npm install -g npm@10.8.2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --verbose

      - name: Build application
        run: npm run build
        
      - name: Build application
        run: npm run build  # Adjust build command as needed
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: "${{ secrets.DOCKER_USERNAME }}/athenium-server:${{ github.sha }}"
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_TAG --push .

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Athenium \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-2-767398068141" \
            --source-bundle S3Key="Athenium/$GITHUB_SHA.zip" \
            --auto-create-application \
            --process

      - name: Deployment Complete
        run: |
          echo "App deployed to AWS Elastic Beanstalk"
