name: Deploy to AWS Elastic Beanstalk with Docker

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --verbose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: "${{ secrets.DOCKER_USERNAME }}/athenium-node-app:latest"
        run: |
          docker buildx build --platform linux/amd64 -t $IMAGE_TAG . --push --progress plain


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload application zip to S3
        run: aws s3 cp path/to/your/application.zip s3://elasticbeanstalk-us-east-2-767398068141/athenium/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Athenium \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-2-767398068141,S3Key=athenium/ \
            --auto-create-application \
            --process


      - name: Deployment Complete
        run: |
          echo "App deployed to AWS Elastic Beanstalk"
