name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - develop  # or the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build  # Adjust according to your build process

      - name: Package the application
        run: zip -r app.zip .  # Change to the correct zip command

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: athenium-node-app
          environment_name: athenium-node-app
          version_label: ${{ github.sha }}
          bucket_name: athenium-server-code-bucket
          bucket_key: my-app.zip
          aws_access_key_id: ${{ secrets.ELASTIC_BEANSTALK_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.ELASTIC_BEANSTALK_SECRET_ACCESS_KEY }}
          region: ${{ secrets.MY_AWS_REGION}}   # Change to your AWS region
