name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --verbose

      - name: Build application
        run: npm run build  # Adjust build command as needed

      - name: Create application zip
        run: zip -r app.zip .  # Creates a zip file containing all files in the current directory

      - name: Upload application zip to S3
        run: aws s3 cp app.zip s3://elasticbeanstalk-us-east-2-767398068141/athenium/$GITHUB_SHA.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Athenium \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-2-767398068141,S3Key=athenium/$GITHUB_SHA.zip \
            --auto-create-application \
            --process

      - name: Deployment Complete
        run: |
          echo "App deployed to AWS Elastic Beanstalk"
